# Generated by Django 5.0.2 on 2024-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('apple_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('apple_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('apple_image', models.ImageField(upload_to='apple/', verbose_name='Ürün Resmi')),
            ],
        ),
    ]
