# Generated by Django 5.0.2 on 2024-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='huawei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huawei_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('huawei_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('huawei_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('huawei_image', models.ImageField(upload_to='huawei/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='kulaklik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kulaklik_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('kulaklik_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('kulaklik_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('kulaklik_image', models.ImageField(upload_to='kulaklik/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='macbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macbook_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('macbook_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('macbook_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('macbook_image', models.ImageField(upload_to='macbook/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='oppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppo_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('oppo_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('oppo_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('oppo_image', models.ImageField(upload_to='oppo/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('other_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('other_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('other_image', models.ImageField(upload_to='other/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='realme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realme_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('realme_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('realme_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('realme_image', models.ImageField(upload_to='realme/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='samsung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samsung_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('samsung_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('samsung_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('samsung_image', models.ImageField(upload_to='samsung/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='xiaomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaomi_name', models.CharField(max_length=100, verbose_name='ürün adı')),
                ('xiaomi_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('xiaomi_description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('xiaomi_image', models.ImageField(upload_to='xiaomi/', verbose_name='Ürün Resmi')),
            ],
        ),
    ]
