# Generated by Django 5.0.2 on 2024-02-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='apple',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
