# Generated by Django 5.0.2 on 2024-02-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_remove_cartitem_cart_remove_cartitem_apple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('apple2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.apple')),
            ],
        ),
    ]
