# Generated by Django 5.0.2 on 2024-02-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_sepetitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SepetItem',
        ),
    ]
