# Generated by Django 5.0.2 on 2024-02-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_delete_sepetitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=50)),
                ('sifre', models.CharField(max_length=50)),
                ('eposta', models.EmailField(max_length=254)),
            ],
        ),
    ]
