# Generated by Django 5.0.2 on 2024-02-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_alter_kullanici_eposta_alter_kullanici_kullanici_adi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kullanici',
        ),
    ]
