# Generated by Django 5.0.2 on 2024-02-17 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0010_apple_battery_capacity_apple_battery_capacity_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='apple_description',
            field=ckeditor.fields.RichTextField(verbose_name='Ürün açıklaması'),
        ),
    ]
