# Generated by Django 5.0.2 on 2024-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_alter_apple_apple_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsung',
            name='battery_capacity',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Pil gücü'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='battery_capacity_range',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Pil gücü aralığı'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='camera_resolution',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Kamera çözünürlüğü'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='camera_resolution_range',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Kamera çözünürlüğü aralığı'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='face_recognition',
            field=models.BooleanField(default=False, verbose_name='Yüz tanıma'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='front_camera',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Ön (Selfie) kamera'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='front_camera_range',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Ön (Selfie) kamera aralığı'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='internal_memory',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Dahili hafıza'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='ram_capacity',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='RAM kapasitesi'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='screen_size',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Ekran boyutu'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='screen_size_range',
            field=models.CharField(default='Bilinmiyor', max_length=50, verbose_name='Ekran boyut aralığı'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='warranty_type',
            field=models.CharField(default='Bilinmiyor', max_length=100, verbose_name='Garanti tipi'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='wireless_charging',
            field=models.BooleanField(default=False, verbose_name='Kablosuz şarj'),
        ),
    ]
