# Generated by Django 5.0.2 on 2024-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0013_huawei_battery_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekilisKodu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True)),
                ('kullanildi_mi', models.BooleanField(default=False)),
            ],
        ),
    ]
